feat: Allow search icon in masthead to be set to a Font Awesome icon.
mmistakes/minimal-mistakes pull request #2774
Opened 2021-01-02 18:11 UTC by rhwood

This is an enhancement or feature.

## Summary

Allow a Font Awesome icon to be used as the search icon instead of the built-in SVG.

## Context

This is not related to any existing issues, but is implemented as optional to:
1. not change the existing default behavior
2. allow other implementations of this site that are avoiding Font Awesome for GDPR and CCPA to continue to do so

2021-01-16 17:46 UTC, iBug commented
Looks good at first glance but I feel uneasy. Maybe `default` is a better choice than `builtin`?

2021-01-17 15:19 UTC, rhwood commented
I avoided using `default` as the default option because
- `default` is non-descriptive ("the default option is default" does not describe the (current) default behavior)
- I want to provide for the possibility that the default changes from the builtin SVG in the future (specifying `builtin` in `_config.yml` is explicitly ensuring the builtin SVG is used even if the default icon changes to something else later)
- I'm assuming that users who want the default behavior and are unconcerned about the possibility of its changing, will not specify this value and leaving it empty (i.e. by explicitly specifying a value, you are not using the default behavior)

2021-01-17 17:19 UTC, iBug requested changes

2021-01-17 17:19 UTC, iBug commented on _includes/masthead.html
> +          <i class="{{ site.search_icon }}"></i>
Can you fix the indentation (add a level) for this line and the 3 lines under (the `<svg>` element)?

2021-01-17 17:50 UTC, iBug approved these changes

2021-05-13 08:44 UTC, rhwood commented
Can this please be explicitly denied with an explanation of why the search icon should be different than every other icon or what needs to be done to use a search icon that matches the style of the other icons instead of quietly ignored without comment?

2021-05-13 12:12 UTC, mmistakes commented
Adding more feature flags to the `_config.yml` is something I try to avoid. I don't really see a compelling reason here to add another one for something that could easily be done with a local `_includes/masthead.html` override.

2021-05-13 12:31 UTC, rhwood commented
It original change wasn’t easily done in that a later upstream change to the masthead.html broke (I forget what, but I had to reimplement this change to incorporate that other change), which is why I proposed this.

Would this be accepted or rejected if it aligned the search icon with the rest of the icon set used without presenting an option to the user?

> On May 13, 2021, at 8:12 AM, Michael Rose ***@***.***> wrote:
> 
> 
> Adding more feature flags to the _config.yml is something I try to avoid. I don't really see a compelling reason here to add another one for something that could easily be done with a local _includes/masthead.html override.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/mmistakes/minimal-mistakes/pull/2774#issuecomment-840515491>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AACISEDLG4TRNYXGAT7C62TTNO63LANCNFSM4VRHH5PQ>.
>

2021-05-13 12:45 UTC, mmistakes commented
Sure, I see value in keeping the icon consistent with the rest of the FA set. So if you want to swap out the inline SVG currently used to match what FA uses that's fine.

2021-06-23 12:06 UTC, merged