Add Homepage link to 404 and improve its apology
mmistakes/minimal-mistakes pull request #2819
Opened 2021-02-10 21:00 UTC by rlaPHOENiX

This is an enhancement or feature.

## Summary

This makes the 404 page more visually appealing as well as more functional, more of a reason to exist.

## Context

N/A

2021-02-10 21:00 UTC, rlaPHOENiX commented
Preview:

![image](https://user-images.githubusercontent.com/17136956/107571602-0c1e6980-6be3-11eb-9e2e-d0504412c279.png)

2021-02-11 03:31 UTC, iBug requested changes

2021-02-11 03:31 UTC, iBug commented on docs/_pages/404.md
> +[Homepage]({{ '/' | absolute_url}})
Recommend:

```diff
-Sorry — we couldn't find what you were looking for.  
-[Homepage]({{ '/' | absolute_url}})
+Sorry — we couldn't find what you were looking for.
+
+[<i class="fas fa-home"></i> Return to homepage]({{ '/' | relative_url}})
```

2021-02-11 15:31 UTC, iBug requested changes

2021-02-11 15:31 UTC, iBug commented on docs/_pages/404.md
> +[<i class="fas fa-home"></i> Return to homepage]({{ '/' | relative_url}})
A small point about coding convention (spacing). Recommended change:

```diff
-[<i class="fas fa-home"></i> Return to homepage]({{ '/' | relative_url}})
+[<i class="fas fa-home"></i> Return to homepage]({{ '/' | relative_url }})
```

2021-05-19 08:38 UTC, rlaphoenix commented
Any further review? potential merge?

2021-07-23 13:37 UTC, mmistakes commented
Thanks for the PR but closing this with the `wontfix` label.
The 404 page here is just an example I'm using for the demo site. It can easily be customized as you have to fit your site's needs.

2021-07-23 13:37 UTC, closed without merging

2021-07-23 13:38 UTC, iBug commented
@mmistakes Honestly I'd say it's better to merge this in. It's certainly an improvement for your docs site, and you know, there could be more 404 links from time to time as the docs are updated and whatever happens...

2021-07-23 13:46 UTC, mmistakes commented
@iBug Don't think I agree. I'm seeing a slightly reworded error text and a home link that already exists in the masthead.