Enable toc sidebar scrolling
mmistakes/minimal-mistakes pull request #2874
Opened 2021-03-11 16:51 UTC by j3soon

This is an enhancement or feature.

## Summary

Enable Table of Content sidebar scrolling as mentioned in issue #1851

This can be achieved by simply adding the followings in `_navigation.scss`:

```css
.sidebar__right.sticky > .toc > .toc__menu {
  overflow-y: auto;
  max-height: calc(100vh - 7em);
}
```

When the toc sidebar is not sticky, this rule will not apply. While if the toc sidebar is sticky (`.sticky`), the `toc_menu`'s height will be limited, and the content will be scrollable with a thin-width scrollbar. I use `max-height` instead of `height` to ensure that short TOCs will not be affected by this rule.

Other scrollbar CSS rules is just for making the scrollbar thin in Chrome/Firefox/... If the default wide scrollbar is not preferred, I can simply remove those style rules and keep the 4 lines above.

### Before

![image](https://user-images.githubusercontent.com/20457146/110819496-35f1ab80-82c9-11eb-9919-38a94573b048.png)

### After

![image](https://user-images.githubusercontent.com/20457146/110819615-4f92f300-82c9-11eb-8172-0bc26fed37d4.png)

## Context

- #1840 
- #1851

2021-03-11 16:55 UTC, iBug requested changes
This doesn't look like good Sass/SCSS. I recommend nesting and relocating them as needed. For example:

Bad SCSS:

```scss
.example-1 {
  color: #aaa;
}

.example-1 .example-2 {
  font-weight: bold;
}

.example-1 .example-2::before {
  position: absolute;
}
```

Good SCSS:

```scss
.example-1 {
  color: #aaa;

  .example-2 {
    font-weight: bold;

	&::before {
	  position: absolute;
	}
  }
}
```

2021-03-11 17:03 UTC, iBug requested changes

2021-03-11 17:03 UTC, iBug commented on _sass/minimal-mistakes/_navigation.scss
> +.sidebar__right.sticky > .toc > .toc__menu {
Also it's going to be ugly on mobile devices where this whole thing is unneeded. Should probably be wrapped inside 

Perhaps [my working code](https://github.com/iBug/iBug-source/blob/cb512482551e516dfe8049c508b5f6550300c337/_sass/toc.scss) ([preview](https://ibug.io/p/23) and [Wayback Machine](https://web.archive.org/web/20210205163606/https://ibug.io/blog/2021/01/linux-container-explained/)) would be a good reference. But keep in mind that those codes are CC BY-SA 4.0 until I actively contribute them to this repo.

2021-03-11 17:19 UTC, j3soon commented
Thanks for the teaching me the good coding style! I have just refactored my code. I have tested the code on Mobile & PC and on Firefox & Chrome.

2021-03-11 17:23 UTC, iBug commented
[`_sidebar.scss`](https://github.com/mmistakes/minimal-mistakes/blob/master/_sass/minimal-mistakes/_sidebar.scss) is definitely a better fit for this change, and that's exactly what I meant by "relocating".

2021-03-11 19:38 UTC, iBug commented
Actually this feature is hard to test for lacking a CSS standard of customizing the scroll bar, and that's why I'm hesitant to submit my code as a PR.

2021-03-11 19:51 UTC, j3soon commented
The CSS style should work for all major browsers except for Internet Explorer:
- [`scrollbar-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width)
- [`::-webkit-scrollbar`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)

If such scrollbar customization is not preferred, maybe we can add the TOC scrolling feature with default scrollbar style?

2021-05-15 07:59 UTC, iBug commented
@mmistakes What are your comments for this feature? It looks and has been looking nice.

2021-05-17 01:07 UTC, mmistakes commented
I'm cool with the PR, but let's remove the custom scrollbar for now and just stick with the default appearance.

2021-05-17 01:08 UTC, mmistakes requested changes
Stick with the default scrollbar appearance and remove the custom `::-webkit-scrollbar-*` declarations and I think we're good to merge it in.

2021-05-17 01:09 UTC, iBug commented
> I'm cool with the PR, but let's remove the custom scrollbar for now and just stick with the default appearance.

I'm not confident about this. The default appearance looks terrible in this context

> ![image](https://user-images.githubusercontent.com/7273074/118419775-9220e380-b6ef-11eb-86c6-69f3ecbf40e7.png)

2021-05-17 01:23 UTC, j3soon commented
I also prefer the custom scrollbar (tested on Chrome/Firefox on PC/Mobile). The default scrollbar looks bad, and without this feature, the overflowing TOC sidebar looks terrible too...

2021-07-16 06:09 UTC, iBug commented
This is nice to have. Any reason we can't proceed?

2021-07-23 14:09 UTC, mmistakes commented on _sass/minimal-mistakes/_sidebar.scss
> +          &::-webkit-scrollbar {
Add blank line to remain consistent with spacing

2021-07-23 14:10 UTC, mmistakes commented on _sass/minimal-mistakes/_sidebar.scss
> +            background: #F0F0F0;
Is this color needed? I want to avoid a situation where this scrollbar doesn't match the native browser one applied to the entire page.

2021-07-23 14:11 UTC, mmistakes commented on _sass/minimal-mistakes/_sidebar.scss
> +            background-color: #CDCDCD;
Similar comments to above. Are the colors needed if they're already picking up the default scrollbar colors?

2021-07-23 14:12 UTC, mmistakes commented on _sass/minimal-mistakes/_navigation.scss
>    img{
While you're editing this file can you add a space between `img` and `{`?

2021-07-23 14:19 UTC, mmistakes commented
The other concern apart from having to maintain custom styles to make the scrollbar match the default one... is the usability of a thin scrollbar on the TOC.

The touch targets are already small on all those TOC links. Throwing in a thin scroll bar seems like we're asking for trouble when used with pointing devices that don't have a scroll wheel/button and you have to actually drag the scrollbar.

2021-07-23 14:26 UTC, mmistakes commented
Which browsers are showing the thicker scrollbars BTW? In my limited tests the TOC scrollbar matches the default system one without any `scrollbar-` CSS to make them thinner or change the colors.

**Chrome:**
![Screen Shot 2021-07-23 at 10 23 37 AM](https://user-images.githubusercontent.com/1376749/126796272-5e59a795-01d0-48cd-b065-24bf3892f8e1.png)

**Safari:**
![Screen Shot 2021-07-23 at 10 24 33 AM](https://user-images.githubusercontent.com/1376749/126796366-59128a55-4b71-41fb-9da6-d0ec1bd0fc53.png)

**Firefox:**
![Screen Shot 2021-07-23 at 10 25 52 AM](https://user-images.githubusercontent.com/1376749/126796549-d82ef40d-e4a2-4cc8-a464-0f823998514a.png)

2021-07-23 17:23 UTC, iBug commented
macOS's default scrollbar looks beautiful, but not that of Windows.

2021-07-23 17:46 UTC, mmistakes commented
Splitting hairs at this point. I'm not at all bothered by Windows' default scrollbar.
I'd rather not customize one scrollbar and not the other. Let's pull out the custom scrollbar CSS so I can merge this in.

Then if someone wants to take a stab at custom scrollbars that affect the entire theme (not just the TOC) and factor in all the skin color variations... I'll look at that PR and provide feedback.

2021-07-29 20:02 UTC, j3soon commented
I've done removing the custom scrollbar styles.

2021-07-30 19:54 UTC, mmistakes approved these changes

2021-07-30 19:54 UTC, merged

2024-05-30 11:01 UTC, mendax1234 commented
@j3soon Seems that using this style I can't let the scroll bar to be round. This is the code I try
```html
.toc {
        .toc__menu {
          overflow-y: auto;
          scrollbar-width: thin;
          max-height: calc(100vh - 7em);
          &::-webkit-scrollbar {
            width: 8px;
          }
          &::-webkit-scrollbar-track {
            background: #F0F0F0;
          }
          &::-webkit-scrollbar-thumb {
            background-color: #CDCDCD;
            border: 1px solid #F0F0F0;
            border-radius: 4px;
          }
        }
      }
```
Thanks for any help!