Do not markdownify title
mmistakes/minimal-mistakes pull request #3113
Opened 2021-08-08 09:58 UTC by lsolesen

Title should not be markdownified. Pull request to fix gh-3094.

## Summary

## Context

2021-08-08 10:01 UTC, iBug requested changes

2021-08-08 10:01 UTC, iBug commented on _includes/seo.html
> +{% assign title_separator = site.title_separator | default: '-' %}
I'd rather keep this line. Liquid `escape_once` doesn't cover the vertical bar. （[Reference](https://www.rubydoc.info/gems/liquid/4.0.0/Liquid/StandardFilters#HTML_ESCAPE_ONCE_REGEXP-constant))

2021-08-08 10:03 UTC, iBug commented
You can add `Fixes #3094` to your PR description so it's automatically closed when this is merged. See <https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword>

2021-08-08 10:13 UTC, lsolesen commented
But why should the vertical bar | be escaped in the seo_title?

If it needs replacing then the replace should probably take place on seo_title together with escape_once instead, as the user might use it as part of the title also.

2021-08-08 10:18 UTC, iBug commented
Well you're right. I couldn't find any necessity to escape the vertical bar. Maybe it was related to Markdown parsing where it would be interpreted as table. Now that you've removed `markdownify`, this escape shouldn't be needed anymore.

2021-08-08 10:18 UTC, iBug approved these changes

2021-08-08 17:54 UTC, mmistakes commented
The `markdownify` filter does serve a purpose as it normalizes titles that may use Markdown to apply emphasis or other "light" formatting.

For example check this test post on master. https://mmistakes.github.io/minimal-mistakes/markdown/markup-title-with-markup/

![Screen Shot 2021-08-08 at 1 54 14 PM](https://user-images.githubusercontent.com/1376749/128641060-353a7fcd-4ea5-4faa-903b-0e44493344ed.png)

The title has a word italized and bolded, and the `<title>` element is readable without Markdown characters appearing.
![Screen Shot 2021-08-08 at 1 51 59 PM](https://user-images.githubusercontent.com/1376749/128641006-c28f96b7-261e-4f97-a00d-b744cbfadff6.png)

This PR breaks that. Now the `<title>` element has all the Markdown syntax there. Markdown titles are probably an edge case, but the theme has had support for them for a long time and this breaks that.

![Screen Shot 2021-08-08 at 1 53 32 PM](https://user-images.githubusercontent.com/1376749/128641048-e404395d-4636-4678-a525-aec7ada212ce.png)

2021-08-08 17:56 UTC, mmistakes commented
A better fix might be to apply the Markdown and replace transforms on `page.title` before the separator and `site.title` are appended. Then it won't do unintended things on the `|` or any other characters that serve a purpose in Markdown.

2021-08-08 17:59 UTC, mmistakes requested changes

2021-08-08 17:59 UTC, mmistakes commented on _includes/seo.html
> -  {%- assign seo_title = seo_title | markdownify | strip_html | strip_newlines | escape_once -%}
Try applying these filters on `page.title` a few lines above before appending the spaces, `title_separator` and `site.title`.

2021-08-13 07:22 UTC, lsolesen commented
Thanks for the comments @iBug and @mmistakes. Here is a new stab on solving the issue.

2022-05-30 10:39 UTC, iBug requested changes

2022-05-30 10:39 UTC, iBug commented on _includes/seo.html
> -  {%- assign seo_title = page.title | append: " " | append: title_separator | append: " " | append: site.title -%}
I think the problem lies here: It assigns `page_title` (with fallback values) only when `page.title` is set, seems like circular logic to me.

2024-05-05 09:45 UTC, iBug commented on _layouts/single.html
> +    {% if page.title %}<meta itemprop="headline" content="{{ page_title }}">{% endif %}
I'm afraid `page_title` as calculated in `seo.html` won't propagate to here.

2024-05-05 10:07 UTC, merged